### ISSUE TITLE
LSP-volar fails to load with latest LSP `master` branch

### ISSUE THREAD

**Issue by deathaxe** [sublimelsp/LSP-volar#132]
LSP-volar fails to load with latest LSP `master` branch.

```
reloading python 3.3 plugin LSP-volar.plugin
Traceback (most recent call last):
  File "C:\Apps\Sublime Text 40xx\Lib\python33\sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Apps\Sublime Text 40xx\Lib\python33\sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "C:\Apps\Sublime Text 40xx\Data\Installed Packages\LSP-volar.sublime-package\plugin.py", line 3, in <module>
ImportError: cannot import name TextDocumentSyncKindIncremental
```

**Comment by rchl** [comment]
The fix is merged (https://github.com/sublimelsp/LSP-volar/pull/130) and will be released as part of the new LSP release (https://github.com/sublimelsp/LSP/issues/2070)
